# The URL the site will be built for
base_url = "https://organicmaps.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feed = true
feed_filename = "rss.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

ignored_content = [".DS_Store"]

[markdown]
external_links_target_blank = true

# Allows to have localized URLs.
[slugify]
paths = "safe"

[extra]
stripe = "https://donate.organicmaps.app/"
github_source = "https://github.com/organicmaps/organicmaps.github.io"

# Default English translation
[translations]
address = "Address"
back = "Back to News"
contact = "Contact Us"
edit_on_github = "Edit on GitHub"
install-appgallery = "Install Organic Maps from Huawei AppGallery"
install-appstore = "Install Organic Maps from the AppStore"
install-googleplay = "Install Organic Maps from Google Play"
install-fdroid="Install Organic Maps from F-Droid"
language = "English"
name = "Name"
token = "Token"
translate_to = "Translate to…"

# Please sort all other translation sections and values in alphabetical order.
[languages.de]
[languages.de.translations]
address = "Adresse"
back = "Zurück zu den Neuigkeiten"
contact = "Kontakt"
edit_on_github = "Auf GitHub bearbeiten"
install-appgallery = "Installiere Organic Maps aus der Huawei AppGallery"
install-appstore = "Installiere Organic Maps aus dem AppStore"
install-googleplay = "Installiere Organic Maps von Google Play"
install-fdroid = "Installiere Organic Maps aus F-Droid"
language = "Deutsch"
name = "Name"
token = "Token"
translate_to = "Übersetzen in…"

[languages.fr]
[languages.fr.translations]
address = "Adresse"
back = "Retour aux actualités"
contact = "Contact"
edit_on_github = "Modifier sur GitHub"
install-appgallery = "Installez Organic Maps depuis l'AppGallery"
install-appstore = "Installez Organic Maps depuis l'AppStore"
install-googleplay = "Installez Organic Maps depuis Google Play"
install-fdroid = "Installez Organic Maps depuis F-Droid"
language = "Français"
name = "Nom"
token = "Jeton"
translate_to = "Traduire en…"

[languages.it]
[languages.it.translations]
address = "Indirizzo"
back = "Indietro"
contact = "Contattaci"
edit_on_github = "Modifica su GitHub"
install-appgallery = "Installa Organic Maps da Huawei AppGallery"
install-appstore = "Installa Organic Maps dall'AppStore"
install-googleplay = "Installa Organic Maps da Google Play"
install-fdroid = "Installa Organic Maps da F-Droid"
language = "Italiano"
name = "Nome"
token = "Token"
translate_to = "Tradurre in…"

[languages.pl]
[languages.pl.translations]
address = "Adres"
back = "Powrót do Nowości"
contact = "Kontakt z nami"
edit_on_github = "Edytuj na GitHubie"
install-appgallery = "Zainstaluj Organic Maps z Huawei AppGallery"
install-appstore = "Zainstaluj Organic Maps z AppStore"
install-googleplay = "Zainstaluj Organic Maps z Google Play"
install-fdroid = "Zainstaluj Organic Maps z F-Droid"
language = "Polski"
name = "Nazwa"
token = "Token"
translate_to = "Przetłumacz na…"

[languages.ru]
[languages.ru.translations]
address = "Адрес"
back = "Назад к новостям"
contact = "Связаться с нами"
edit_on_github = "Редактировать на GitHub"
install-appgallery = "Установите Organic Maps из Huawei AppGallery"
install-appstore = "Установите Organic Maps из AppStore"
install-googleplay = "Установите Organic Maps из Google Play"
install-fdroid = "Установите Organic Maps из F-Droid"
language = "Русский"
name = "Название"
token = "Токен"
translate_to = "Перевести на…"

[languages.tr]
[languages.tr.translations]
address = "Adres"
back = "Haberlere geri dön"
contact = "Bize ulaşın"
edit_on_github = "GitHub'da Düzenle"
install-appgallery = "Organic Maps'i Huawei AppGallery'den İndir"
install-appstore = "Organic Maps'i AppStore'dan İndir"
install-googleplay = "Organic Maps'i Google Play'den İndir"
install-fdroid = "Organic Maps'i F-Droid'den İndir"
language = "Türkçe"
name = "İsim"
token = "Token"
translate_to = "Tercüme et…"

[languages.id]
[languages.id.translations]
address = "Alamat"
back = "Kembali ke Berita"
contact = "Hubungi Kami"
edit_on_github = "Edit di GitHub"
install-appgallery = "Instal Organic Maps dari Huawei AppGallery"
install-appstore = "Instal Organic Maps dari AppStore"
install-googleplay = "Instal Organic Maps dari Google Play"
install-fdroid = "Instal Peta Organik dari F-Droid"
language = "Bahasa Indonesia"
name = "Nama"
token = "Token"
translate_to = "Terjemahkan ke…"

[languages.cs]
[languages.cs.translations]
address = "Adresa"
back = "Zpět na novinky"
contact = "Kontaktujte nás"
edit_on_github = "Upravit na GitHubu"
install-appgallery = "Instalace aplikace Organic Maps z galerie aplikací Huawei"
install-appstore = "Instalace aplikace Organic Maps z AppStore"
install-googleplay = "Instalace Organic Maps z Google Play"
install-fdroid = "Instalace Organic Maps z F-Droid"
language = "čeština"
name = "Název"
token = "Token"
translate_to = "Přeložit do…"

[languages.pt-BR.translations]
address = "Endereço"
back = "Voltar às Notícias"
contact = "Contate-nos"
edit_on_github = "Editar no GitHub"
install-appgallery = "Instale Organic Maps a partir da Huawei AppGallery"
install-appstore = "Instale Organic Maps a partir da AppStore"
install-googleplay = "Instale Organic Maps a partir da Google Play"
install-fdroid = "Instale Organic Maps a partir do F-Droid"
language = "Português (Brazil)"
name = "Nome"
token = "Token"
translate_to = "Traduzir para…"

[languages.es.translations]
address = "Dirección"
back = "Volver a Noticias"
contact = "Contacte con nosotros"
edit_on_github = "Editar en GitHub"
install-appgallery = "Instalar Organic Maps desde la AppGallery de Huawei"
install-appstore = "Instalar Organic Maps desde el AppStore"
install-googleplay = "Instalar Organic Maps desde Google Play"
install-fdroid = "Instalar Organic Maps desde F-Droid"
language = "Español"
name = "Nombre"
token = "Ficha"
translate_to = "Traducir a…"

[languages.nl.translations]
address = "Adres"
back = "Terug naar Nieuws"
contact = "Contacteer ons"
edit_on_github = "Bewerken op GitHub"
install-appgallery = "Installeer Organic Maps in de Huawei AppGallery"
install-appstore = "Installeer Organic Maps in de AppStore"
install-googleplay = "Installeer Organic Maps op Google Play"
install-fdroid = "Installeer Organic Maps op F-Droid"
language = "Dutch"
name = "Naam"
token = "Token"
translate_to = "Vertalen naar…"

[languages.eu.translations]
address = "Helbidea"
back = "Back to News"
contact = "Harremanetan jarri"
edit_on_github = "Editatu GitHub-en"
install-appgallery = "Install Organic Maps from Huawei AppGallery"
install-appstore = "Install Organic Maps from the AppStore"
install-googleplay = "Install Organic Maps from Google Play"
install-fdroid = "Install Organic Maps from F-Droid"
language = "Euskara"
name = "Izena"
token = "token"
translate_to = "Itzuli…"

[languages.hu.translations]
address = "Cím"
back = "Vissza a Hírekhez"
contact = "Kapcsolat"
edit_on_github = "Szerkesztés a GitHubon"
install-appgallery = "Telepítse az Organic Maps-et a Huawei AppGalériából"
install-appstore = "Telepítse az Organic Maps-et az AppStore-ból"
install-googleplay = "Telepítse az Organic Maps-et a Google Play-ről"
install-fdroid = "Telepítse az Organic Maps-et az F-Droidról"
language = "Magyar"
name = "Név"
token = "Token"
translate_to = "Fordítás…"

[languages.hi.translations]
address = "पता"
back = "ख़बरों पर वापस जाएं"
contact = "संपर्क करें"
edit_on_github = "गिटहब पर संपादित करें"
install-appgallery = "Huawei AppGallery से ऑर्गेनिक मैप इंस्टॉल करें"
install-appstore = "AppStore से ऑर्गेनिक मैप इंस्टॉल करें"
install-googleplay = "गूगल प्ले से ऑर्गेनिक मैप इंस्टॉल करें"
install-fdroid = "F-Droid से ऑर्गेनिक मैप्स इंस्टॉल करें"
language = "अंग्रेजी"
name = "नाम"
token = "टोकन/Token"
translate_to = "अनुवाद करने के लिए…"

[languages.uk.translations]
address = "Адреса"
back = "Назад до Новин"
contact = "Контакти"
edit_on_github = "Редагувати на GitHub"
install-appgallery = "Встановіть Organic Maps з Huawei AppGallery"
install-appstore = "Встановіть Organic Maps з AppStore"
install-googleplay = "Встановіть Organic Maps з Google Play"
install-fdroid = "Встановіть Organic Maps з F-Droid"
language = "Українська"
name = "Назва"
token = "Токен"
translate_to = "Перекласти на…"

[languages.ca.translations]
address = "Adreça"
back = "Torna a Notícies"
contact = "Contacte"
edit_on_github = "Edita a GitHub"
install-appgallery = "Instal·leu l’Organic Maps des de l’AppGallery de Huawei"
install-appstore = "Instal·leu l’Organic Maps des de l’AppStore"
install-googleplay = "Instal·leu l’Organic Maps des del Google Play"
install-fdroid = "Instal·leu l’Organic Maps des del F-Droid"
language = "Català"
name = "Nom"
token = "Testimoni"
translate_to = "Traduir a…"
