# The URL the site will be built for
base_url = "https://organicmaps.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feed = true
feed_filename = "rss.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

ignored_content = [".DS_Store"]

[markdown]
external_links_target_blank = true

# Allows to have localized URLs.
[slugify]
paths = "safe"

[extra]
stripe = "https://donate.organicmaps.app/"

# Default English translation
[translations]
address = "Address"
back = "Back to News"
contact = "Contact Us"
install-appgallery = "Install Organic Maps from Huawei AppGallery"
install-appstore = "Install Organic Maps from the AppStore"
install-googleplay = "Install Organic Maps from Google Play"
install-fdroid="Install Organic Maps from F-Droid"
language = "English"
name = "Name"
token = "Token"

# Please sort all other translation sections and values in alphabetical order.
[languages.de]
[languages.de.translations]
address = "Adresse"
back = "Zurück zu Neuigkeiten"
contact = "Kontakt"
install-appgallery = "Organic Maps aus der Huawei AppGallery installieren"
install-appstore = "Installiere Organic Maps aus dem AppStore"
install-googleplay = "Organic Maps von Google Play installieren"
install-fdroid="Organic Maps von F-Droid installieren"
language = "Deutsch"
name = "Name"
token = "Token"

[languages.it]
[languages.it.translations]
address = "Indirizzo"
back = "Indietro"
contact = "Contattaci"
install-appgallery = "Installa Organic Maps da Huawei AppGallery"
install-appstore = "Installa Organic Maps dall'AppStore"
install-fdroid="Installa Organic Maps da F-Droid"
install-googleplay = "Installa Organic Maps da Google Play"
language = "Italiano"
name = "Nome"
token = "Token"

[languages.pl]
[languages.pl.translations]
address = "Adres"
back = "Z powrotem"
contact = "Kontakt"
install-appgallery = "Zainstaluj Organic Maps z Huawei AppGallery"
install-appstore = "Zainstaluj Organic Maps z App Store"
install-fdroid="Zainstaluj Organic Maps z F-Droid"
install-googleplay = "Zainstaluj Organic Maps z Google Play"
name = "Nazwa"
language = "Polski"
token = "Token"

[languages.ru]
[languages.ru.translations]
address = "Адрес"
back = "Назад"
contact = "Связаться с нами"
install-appgallery = "Установить Organic Maps из Huawei AppGallery"
install-appstore = "Установить Organic Maps из Apple AppStore"
install-fdroid="Установить Organic Maps из F-Droid"
install-googleplay = "Установить Organic Maps из Google Play"
language = "Русский"
name = "Название"
token = "Токен"

[languages.tr]
[languages.tr.translations]
address = "Adres"
back = "Haberlere geri dön"
contact = "Bize ulaşın"
install-appgallery = "Organic Maps'i Huawei AppGallery'den İndir"
install-appstore = "Organic Maps'i AppStore'dan İndir"
install-fdroid="Organic Maps'i F-Droid'den İndir"
install-googleplay = "Organic Maps'i Google Play'den İndir"
language = "Türkçe"
name = "İsim"
token = "Token"
